{% set name = "ukcensusapi" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5a274fbe882f3feba9e2f8ca65866b94bf7dfbc7fc2e9cc40cf3e770ce6613d

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - requests

test:
  imports:
    - ukcensusapi.Nomisweb
    - ukcensusapi.NRScotland
    - ukcensusapi.NISRA
    - ukcensusapi.Query

about:
  home: https://github.com/virgesmith/UKCensusAPI
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: 'UK Census Data queries and downloads from python or R'
  dev_url: https://github.com/virgesmith/UKCensusAPI

extra:
  recipe-maintainers:
    - virgesmith
