{% set name = "ukcensusapi" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a83c7fb00414798ed2a20e49de1163bb05b48daeff6b11ae967e7c9e699729ab

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python>=3.6
    - pip
  run:
    - python>=3.6
    - numpy
    - pandas
    - requests

test:
  imports:
    - ukcensusapi.Nomisweb
    - ukcensusapi.NRScotland
    - ukcensusapi.NISRA
    - ukcensusapi.Query

about:
  home: https://github.com/virgesmith/UKCensusAPI
  license: MIT
  license_family: MIT
  license_file: LICENCE.md
  summary: UK Census Data queries and downloads from python or R
  dev_url: https://github.com/virgesmith/UKCensusAPI

extra:
  recipe-maintainers:
    - virgesmith
