travis:
  secure:
    BINSTAR_TOKEN: XoEiO3NYj/IznnGy01EpqFskmV9FR6rDeylMvm88AiQshLdP/MDhkRjy0OjsJHJHRQAzrz2tFnap33w+/IyIHKHud9Ws/L/W9SnGQte4fQDR4bV09Zj5/OUzYXxFd/BmZ77E/NjY4GQwQi3y7ibgrd68cA1J596eTen/rCvaclModavdUuVqxX+kliKVzD60Bo1afqBpKIpXZNtZvr2CIhZTP7PJci7Pp2kqmWkL25DGcqDimg1SlKYfGfuKySV8b0U/sK4u9+kO6lCwd5cJ9nCwgKaobYt1yi3oFUvnSHTVyxQO97aywnByFxi/8y4y2P3xAw1e4D5QwrV7pdXSGSlhokyMgaRGOdfrFA6bQQGN9HLgcyl4kuyaYuCTIkzkrrJKZO26cCcq4uGE+8JSHVLbKHiiP3h8pKXfUHnqPNdkYhcUvXh/xeBpx0MBz8wISXhKlowjkHxK9RWIIXB0UK0o1RIExlHocSefdVGrwczZntAnUuRpHj/SQLoENLGYpZGN0+hRgHO9vc2jr0zGzb83DrrdjALwZHC9wtytNZ7jgnf2Nrfsv/2YIZxkciyU9P/BbH83iadV7m1LqpxcY1MY0UbMgYH4vWdz+ind8yE27HiY/ZU5xZpFvQ+0o5QpJD342uHRIuCYuDuemDaqG24fivyciFAzrnXIDNw/xzg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
