travis:
  secure:
    BINSTAR_TOKEN: e/32vkI9naheR7X6rga1nbeGjvXK3XkfJtVhCWGSkGtSAx4Mohbh3FEAZSVqtyvkfmh7SGVUr30SXAD0e2vyc4kTpM2qScBz07xleLVKwPwolX9GYWWxRdXnmyjf+XoBKYjnWbG2xZjOtgzeIwtrVEfWXO7B+1NiHBr3oJhj0T9wU426LMIOraPf81rH96ILV/v1RsbzFpN41pOX4LSBWQyJ3HJixyIzW4nhkuhlWlB5ohs650dKz6lkgrbO/f57CRJOYbhYL6a99X0kPpBtfnS4ugDORAbLtLWIQfzPw/srcF8fjQv3T5lm+jMzpLD7HtFbCTgZnq50a7+RbiDMs2G/A3r3btVhD4GIBMHObI+nfPqjsYROoektDGbxyq7paz1STZ+ZHt9hqXjZAZdCblefIWwvUEl7VjGWwIozJIvXzwBXjvldPaj21896eAIDyxChgrDwGJVvxA+ENrV8unysPswa3kqS44Up4O3GdIJj7t6ZhuV8uIBot/veCLNdlZVZLNOXSubYJ1XSEpOrCUvczEvD28QwoeGOAHq/jrOPEd4N0w0HEFDBuKnP+3wGteA9Oyc8q/Ch/q2BRj9djB//WcviMt/9vz6ZZGC0Tatl7mhexiKGja76W6PtroVEidsAuABW+aJ1p2znpd6C7y1s7mDvrpC8MWXliLd2MW4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
